# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: mischa-quote
- name: passed_tag
  value: $[variables.tag]

pool:
  vmImage: ubuntu-latest

stages:
- stage: submit_pr
  jobs:
    - job: submit_pr
      steps:
        - script: echo $(passed_tag)
        - checkout: self
          persistCredentials: true
        - script: |
            sed -i "s/tag:.*/tag: $(passed_tag)/" values.yaml 

        - script: |
            git config --global user.email "mischa@pipeline.com"
            git config --global user.name "Mischa Pipeline"
            git add .
            git commit -m "Update tag value to $(passed_tag)"
            git push origin main



