apiVersion: v1
kind: Service
metadata:
  name: static-quote
  namespace: static-quote
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30010
  selector:
    app: static-quote
